class Indentable(object):
    indentation: str
    def __init__(self, level: int): ...
    @property
    def level(self) -> int: ...
    @level.setter
    def level(self, level: int): ...
    @property
    def indent(self) -> str: ...
    @property
    def nextIndent(self) -> Indentable: ...
    def __str__(self) -> str: ...
