from typing import Union

KEYWORDS: tuple[str, ...]

_AnyNameable: Union = Nameable | str

def getName(nameable: _AnyNameable) -> str: ...

class Nameable(object):
    def __init__(self, name: _AnyNameable): ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, name: str): ...
    def __str__(self) -> str: ...
    def __hash__(self) -> int: ...
